#+TITLE: DHIS2 Demo – IN5320 – Oblig 3
#+AUTHOR: <Ditt navn>
#+OPTIONS: toc:nil

* Introduksjon
Dette prosjektet er en enkel DHIS2-app som lar deg:
- Bla gjennom dataelementer for et valgt dataset
- Legge inn nye verdier (insert)
- Se en oversikt over tilgjengelige datasett og deres dataelementer
- Endre dataset, orgunit og periode via et innstillingsvindu

Dette prosjektet er laget ved hjelp av [[https://github.com/dhis2/app-platform][DHIS2 Application Platform]], 
som gir en grunnstruktur og verktøy for å utvikle apper til DHIS2.

* Installasjon
** Forutsetninger
Før du kan kjøre prosjektet, må du ha:
- [[https://nodejs.org/en][Node.js]] (versjon 18 eller nyere anbefales)
- [[https://classic.yarnpkg.com/lang/en/docs/install][Yarn]] (anbefalt) eller npm
- Tilgang til en DHIS2-instans (f.eks. DHIS2 Play serveren) og app-adapter-konfigurasjon

** Avhengigheter
Prosjektet bruker blant annet:
- =@dhis2/app-runtime=
- =@dhis2/ui=
- =react=, =react-dom=
- =vite=

* Oppsett
** 1. Klon repoet
#+begin_src shell
git clone <repo-url>
cd <repo-mappe>
#+end_src

** 2. Installer avhengigheter
Med yarn:
#+begin_src shell
yarn install
#+end_src

Eller med npm:
#+begin_src shell
npm install
#+end_src

** 3. Kjør utviklingsserver
#+begin_src shell
yarn start
#+end_src

Eller med npm:
#+begin_src shell
npm run start
#+end_src

Kjører appen i utviklingsmodus.  
Åpne [[http://localhost:3000]] i nettleseren for å se den.  
Siden oppdateres automatisk ved filendringer, og eventuelle lint-feil vises i konsollen.

** 4. Kjør tester
#+begin_src shell
yarn test
#+end_src

Starter testrunneren og kjører alle tilgjengelige tester i =/src=.  
Se [[https://platform.dhis2.nu/#/scripts/test][dokumentasjon om testing]] for mer informasjon.

** 5. Bygg for produksjon
#+begin_src shell
yarn build
#+end_src

Bygger appen for produksjon i mappen =build=.  
React bygges i produksjonsmodus, koden optimaliseres, minifiseres og filnavnene inkluderer hashes.  
En distribusjonsklar =.zip=-fil finnes i =build/bundle=.

Se [[https://platform.dhis2.nu/#/scripts/build][dokumentasjon om bygging]] for mer informasjon.

** 6. Deploy til DHIS2-instans
#+begin_src shell
yarn deploy
#+end_src

Laster opp bygget app til en kjørende DHIS2-instans.  
Du vil bli bedt om å angi server-URL, brukernavn og passord for en DHIS2-bruker med *App Management*-rettigheter.  
NB: Må kjøres etter =yarn build=.  

Se [[https://platform.dhis2.nu/#/scripts/deploy][dokumentasjon om deploy]] for mer informasjon.

* Viktig ved bruk mot IN5320-testserveren
For å teste appen mot riktig DHIS2-instans må portalen kobles til med:
#+begin_src shell
npx dhis-portal --target=https://data.research.dhis2.org/in5320/
#+end_src
Dette sikrer at API-kallene går mot korrekt server.

* Bruk
Når appen kjører:
1. Bruk fanene ~Browse~, ~Insert~ og ~Datasets~ for å navigere.
2. Klikk ~Settings~ for å velge dataset, orgunit og periode.
3. I ~Browse~ vises dataelementene med verdier.
4. I ~Insert~ kan du legge til nye verdier i valgt dataset.
5. I ~Datasets~ får du oversikt over alle datasett og deres dataelementer.

* Mer informasjon
- [[https://platform.dhis2.nu][DHIS2 Application Platform Documentation]]
- [[https://runtime.dhis2.nu][DHIS2 Application Runtime Documentation]]
- [[https://reactjs.org/][React documentation]]
